### PR TITLE
Added encodeMessage method to weather13

### PR DESCRIPTION
**Pull request by peterstrapp**
To send messages to weather station display.

### CODE REVIEW

**Comment by Icesory** [comment]
I dont know a device to send weather protocols. What is your purpose in this case?

**Comment by sweetpi** [comment]
Ho do you use this?

**Comment by peterstrapp** [comment]
This change was to send weather data to a display such as [this one](http://www.weathersnob.com/assets_c/2011/12/digphotoweatherstation-thumb-400x440-33445.jpg) from a raspberry pi using a 433Mhz transmitter.

**Comment by Icesory** [comment]
This is clear. But how do you want to send it from the pi? It exist no device in pimatic which can send weather protocols. And how do you want to fill a the message with data?

Eventually we can implement a bridge between pimatic-openweather and pimatic-homeduino. 
The idea is definitely interesting.

**Comment by peterstrapp** [comment]
I see. I'm wrapping homeduinojs for use in [node-red](http://nodered.org/). I've created a [node](https://github.com/peterstrapp/node-red-contrib-rfsender) that calls [board.rfControlSendMessage](https://github.com/pimatic/homeduinojs/blob/master/src/board.coffee#L188), it accepts messages from other node-red nodes.

**Pull request closed without merging**
