### PR TITLE
update doorbell3 coffee and test

### PR DESCRIPTION
**Pull request by primatic**
updated test sequence for doorbell 3

### CODE REVIEW

**Comment by primatic** [comment]
got my arduino uno, hooked it up to rf receiver and transmitter, helas does the debug output not show anything when the physical doorbell is pressed. Probably this protocol is not supported?

**Comment by primatic** [comment]
arduino receives and transmits other protocols, and even sends the doorbell3 protocol, but does not receive it.....

**Comment by sweetpi** [comment]
What's the status of the protocol, do you have still trouble receiving the pulse sequence?

**Comment by primatic** [comment]
I did not investigate further why the arduino can receive data from other sensors but fails to receive the doorbell3 protocol. [It is able to transmit that protocol]. I checked the https://github.com/pimatic/homeduino instructions and did not see any recent change nor in instructions, nor in the RFControl library. 

[I ordered an arduino and rf transmitter/receiver to get the 'debug' info of the protocol, but it seems that the protocol is not supported]

Originally I reconstructed the protocol using a 433 receiver hooked up to the mic input of my computer to record the pulse sequences. From that I constructed the protocol. The protocol is now used to trigger the doorbell as signal/alarm when network is down.
Attached I have a recording, which could give you a clue on why reception of the doorbell3 protocol with a homeduino fails.

[Uploading 433 doorbel wp515s 4 (shorted).zip…]()

**Comment by primatic** [comment]
(continued) I found the simulate tool of the homeduino (https://github.com/pimatic/RFControl/tree/master/simulate). When I enter the protocol timing as
`295, 590,295,590,295,590,295,590,295,  295,590,295,590,295,590,590,295,295,590,590,295,295,590,9864,`
`295, 590,295,590,295,590,295,590,295,  295,590,295,590,295,590,590,295,295,590,590,295,295,590,9864,`
`295, 590,295,590,295,590,295,590,295,  295,590,295,590,295,590,590,295,295,590,590,295,295,590,9864,`
`295, 590,295,590,295,590,295,590,295,  295,590,295,590,295,590,590,295,295,590,590,295,295,590,9864,`
`295, 590,295,590,295,590,295,590,295,  295,590,295,590,295,590,590,295,295,590,590,295,295,590,9864,`
`295, 590,295,590,295,590,295,590,295,  295,590,295,590,295,590,590,295,295,590,590,295,295,590,9864`

the simulate output result is
` => start recoding`
`STATUS_RECORDING_0: rec_pos=  0 pack_pos=  0 duration=   73`
`STATUS_RECORDING_0: rec_pos=  1 pack_pos=  1 duration=  147`
`STATUS_RECORDING_0: rec_pos=  2 pack_pos=  2 duration=   73`
`STATUS_RECORDING_0: rec_pos=  3 pack_pos=  3 duration=  147`
`STATUS_RECORDING_0: rec_pos=  4 pack_pos=  4 duration=   73`
`STATUS_RECORDING_0: rec_pos=  5 pack_pos=  5 duration=  147`
`STATUS_RECORDING_0: rec_pos=  6 pack_pos=  6 duration=   73`
`STATUS_RECORDING_0: rec_pos=  7 pack_pos=  7 duration=  147`
`STATUS_RECORDING_0: rec_pos=  8 pack_pos=  8 duration=   73`
`STATUS_RECORDING_0: rec_pos=  9 pack_pos=  9 duration=   73`
`STATUS_RECORDING_0: rec_pos= 10 pack_pos= 10 duration=  147`
`STATUS_RECORDING_0: rec_pos= 11 pack_pos= 11 duration=   73`
`STATUS_RECORDING_0: rec_pos= 12 pack_pos= 12 duration=  147`
`STATUS_RECORDING_0: rec_pos= 13 pack_pos= 13 duration=   73`
`STATUS_RECORDING_0: rec_pos= 14 pack_pos= 14 duration=  147`
`STATUS_RECORDING_0: rec_pos= 15 pack_pos= 15 duration=  147`
`STATUS_RECORDING_0: rec_pos= 16 pack_pos= 16 duration=   73`
`STATUS_RECORDING_0: rec_pos= 17 pack_pos= 17 duration=   73`
`STATUS_RECORDING_0: rec_pos= 18 pack_pos= 18 duration=  147`
`STATUS_RECORDING_0: rec_pos= 19 pack_pos= 19 duration=  147`
`STATUS_RECORDING_0: rec_pos= 20 pack_pos= 20 duration=   73`
`STATUS_RECORDING_0: rec_pos= 21 pack_pos= 21 duration=   73`
`STATUS_RECORDING_0: rec_pos= 22 pack_pos= 22 duration=  147`
`STATUS_RECORDING_0: rec_pos= 23 pack_pos= 23 duration= 2466 => restart package => start recoding`
`STATUS_RECORDING_0: rec_pos=  0 pack_pos=  0 duration=   73`
`STATUS_RECORDING_0: rec_pos=  1 pack_pos=  1 duration=  147`
--%<----

which gives me the impression that the protocol is not receive-able by the homeduino. Any clue how to 'fix' this?

**Comment by mwittig** [comment]
What is the status of this please? The 'doorbeel3' protocol appears to be broken. Did you manage to fix this?

**Comment by primatic** [comment]
Transmission of the doorbell3 protocol succeeds; reception fails. Simulation using the simulator indicates that reception of this protocol is not supported by the homeduino. I'll raise an issue for this.

**Comment by primatic** [comment]
doorbell3 test (finally) fixed

**Comment by primatic** [comment]
added more testcases for doorbell3

**Pull request merged**
