### PR TITLE
Added pir6.js

### PR DESCRIPTION
**Pull request by xCite1986**
Added Protocol pir6.js for this type of [PIR's](http://www.importe-uzman.de//funkalarmanlagen-bewegungsmelder-kompatibel-zonen-anlage-p-4476.html?osCsid=0cd6b4f19f537ee2fd0a0afcf6a33f30) and [window-contact-sensors](http://www.importe-uzman.de//funk-alarmanlagen-glasbruchmelder-kompatibel-zonen-anlage-p-4479.html?osCsid=0cd6b4f19f537ee2fd0a0afcf6a33f30)

### CODE REVIEW

**Comment by mwittig** [comment]
Thanks for you PR. Note however, the protocol must be written in Coffeescript. The JS will be generated. Moreover, you should add test cases for your protocol. See https://github.com/pimatic/rfcontroljs#adding-a-new-protocol for details

**Comment by sweetpi** [comment]
waiting for coffee file and tests.

**Comment by xCite1986** [comment]
@mwittig 

I'm sorry, I 'm not familiar with coffee script. with my experience I destroy so only my pimatic-homeduino ^^

you could find some debug-outputs in my issue  
https://github.com/pimatic/rfcontroljs/issues/36

short summary what I've done: the pir was detected as switch6 and switch8, so I've taken this protocol, clone'd it and  rewrite to a pir...

**Comment by mwittig** [comment]
I have implemented the coffeescript files and add them to your fork for futher reference. Unfortunately your protocol cannot be decoded with the test data I found in #36 If you have chance to investigate this please do some testing on your fork or get back to me with more test data. I am closing the PR for now.

**Pull request closed without merging**
