### PR TITLE
New protocol : doorbell1 for ADEO hardware

### PR DESCRIPTION
**Pull request by Yves911**
Currently i am using a SWITCH, but a doorbell device could be better. Door Bell could:
- receive message (ie bell activated from the remote), maybe a autoreset thing could be useful (like for contact or PIR)
- send a message (ie bell triggered via pimatic)

For now switch is ok and still enough

### CODE REVIEW

**Comment by Icesory** [comment]
This generally a bad idea to map the protocol
```
    '0101': '1' #binary 1
    '1010': '1' #binary 1
    '0110': '0' #binary 0
```
break it down to this
```
    '10': '1' #binary 1
    '01': '0' #binary 0
```
and i my opinion you should use id and unit instead of systemcode and programmcode. Most of the protocols use this.

**Comment by Icesory** [comment]
And you have forgot to generate the .js files

**Comment by Yves911** [comment]
Thanks @Icesory i don't want to change the binary things (because i don't want to break it) and don't know how to generate the .js file

**Comment by Icesory** [comment]
I have changed the binary part to an more generic.
You must only change your id and unit.

**Comment by Yves911** [comment]
@Icesory thanks i see that you did the changes. 
I tried to refresh my pimatic-homeduino (and rfcontroljs) today BUT i still can't see doorbell1.js in lib/protocols. What i am doing wrong?

**Comment by Icesory** [comment]
You can pull the git rep. At the moment It isn't in the official npm

**Comment by Yves911** [comment]
Okay tested it today and all works fine: big THANKS !!

**Pull request merged**
