### PR TITLE
add switch25 (oh haus switch)

### PR DESCRIPTION
**Pull request by abmantis**
New switch from Oh!Haus & Co. (yes, it is written like that) .
I couldn't find any conversion pattern, so I had to use the pulses directly :(

Hera are some codes for the switches if anyone wants to try to find patterns:

1 ON: 01010110010101100101011001100110011001010101101002
1 OFF: 01010110010101100101011001100110011001011010010102
1 BOTH: 01010110010101100101011001100110011001010101010102
2 ON: 01010110010101100101011001100110010101100101101002
2 OFF: 01010110010101100101011001100110010101101010010102
2 BOTH: 01010110010101100101011001100110010101100101010102
3 ON: 01010110010101100101011001010110011001100101101002
3 OFF: 01010110010101100101011001010110011001101010010102
3 BOTH: 01010110010101100101011001010110011001100101010102

### CODE REVIEW

**Comment by sweetpi** [comment]
Thanks again. Merged manually as switch28!.

**Comment by mwittig** [comment]
@abmantis Can you please post a link to the product page of the Oh!Haus & Co switch. Thanks

**Comment by abmantis** [comment]
I couldn't find any official page, but this is it: http://www.pxsl.es/tienda/product_info.php?manufacturers_id=11&products_id=193&osCsid=s1jf1t53t20olbhqigim77n916

And here is a video: https://www.youtube.com/watch?v=LydduaDIDrE

**Comment by mwittig** [comment]
Thanks for the swift reply! I'll add this to the list of supported hardware.

**Comment by mwittig** [comment]
The video also shows the dimming function. Did you consider to support this, too?

**Comment by abmantis** [comment]
@mwittig It is already supported. Dimming is done by simply pressing the On or Off buttons repeatedly. Each time the dimmer receives an "On" command, it dimms up a bit. Pressing both On and Off simultaneously (command "Both" on rfcontroljs), it turns off. I has no way of setting the dimming value directly (at least that I know of)

**Comment by mwittig** [comment]
Thanks, got it. So, one should setup a HomeduinoRFButtonsDevice to use the full functionality

**Comment by abmantis** [comment]
Yes, that is right. With 3 buttons: On, Off, Both (if you need this for the dimmer).

Offtopic: could you please check the message I sent you in pimatic forum chat? Thanks.

**Pull request closed without merging**
