### PR TITLE
switch16.js

### PR DESCRIPTION
**Pull request by mhilcher**
New protocol for wireless remote control switch "Intertek 22541673" which can be bought in Germany for example in "Bauhaus". It's a set of 3 switches with one remote. The switches are self learning. I have only 1 set so that I do not exactly know where the id begins. At least this protocol is working for my switches.

### CODE REVIEW

**Comment by Icesory** [comment]
Can you pls post all your debug outputs from Homeduino for all buttons. 
Your protocol implementation looks not right.

**Comment by mhilcher** [comment]
Switch A
On:
```
RF receive 260 2672 1270 10544 0 0 0 0 010200020002000002000200020200020002000200020000020200000202000200020002000200020002000200000200020200000200020200020002000200020003
```
Off:
```
RF receive 260 2676 1274 10548 0 0 0 0 010200020002000002000200020200020002000200020000020200000202000200020002000200020002000200000200020200000200020002020002000200020003
```
Switch B
On:
```
RF receive 258 2680 1276 10560 0 0 0 0 010200020002000002000200020200020002000200020000020200000202000200020002000200020002000200000200020200000200020200020002000200000203
```
Off:
```
RF receive 257 2672 1276 10536 0 0 0 0 010200020002000002000200020200020002000200020000020200000202000200020002000200020002000200000200020200000200020002020002000200000203
```
Switch C
On:
```
RF receive 261 2688 1275 10560 0 0 0 0 010200020002000002000200020200020002000200020000020200000202000200020002000200020002000200000200020200000200020200020002000002020003
```
Off:
```
RF receive 259 2684 1280 10564 0 0 0 0 010200020002000002000200020200020002000200020000020200000202000200020002000200020002000200000200020200000200020002020002000002020003
```

Looks good for me..

**Comment by Icesory** [comment]
You use definitely the wrong patterns. I merge it later and fix it.

**Comment by mhilcher** [comment]
Sure, it’s hard to find a pattern if you have just one set with the same id and different units.
The manufacturer writes about 67 million possible codes, which is 2^26.
That means that 26 bytes would be used for coding, but what they don’t write is if this is a combination of id and unit or just the id, I guess it’s just the id, because then it would make sense to use 4 digits to decode 1 byte.
26 bytes for id and 4 bytes for the unit, 1 byte each state and inverted state makes 32 bytes = 128 digits. 01 at the start and 03 at the end would make 132 digits = pulses.

So I think you are right and I’m using the wrong pattern.
With 4 digits it looks like this (first row for each switch is on, second is off):
```
A
RF receive 260 2672 1270 10544 0 0 0 0 01 0200 0200 0200 0002 0002 0002 0200 0200 0200 0200 0200 0002 0200 0002 0200 0200 0200 0200 0200 0200 0200 0200 0002 0002 0200 0002 0002 0200 0200 0200 0200 0200  03

RF receive 260 2676 1274 10548 0 0 0 0 01 0200 0200 0200 0002 0002 0002 0200 0200 0200 0200 0200 0002 0200 0002 0200 0200 0200 0200 0200 0200 0200 0200 0002 0002 0200 0002 0002 0002 0200 0200 0200 0200  03

B
RF receive 258 2680 1276 10560 0 0 0 0 01 0200 0200 0200 0002 0002 0002 0200 0200 0200 0200 0200 0002 0200 0002 0200 0200 0200 0200 0200 0200 0200 0200 0002 0002 0200 0002 0002 0200 0200 0200 0200 0002 03

RF receive 257 2672 1276 10536 0 0 0 0 01 0200 0200 0200 0002 0002 0002 0200 0200 0200 0200 0200 0002 0200 0002 0200 0200 0200 0200 0200 0200 0200 0200 0002 0002 0200 0002 0002 0002 0200 0200 0200 0002 03

C
RF receive 261 2688 1275 10560 0 0 0 0 01 0200 0200 0200 0002 0002 0002 0200 0200 0200 0200 0200 0002 0200 0002 0200 0200 0200 0200 0200 0200 0200 0200 0002 0002 0200 0002 0002 0200 0200 0200 0002 0200 03

RF receive 259 2684 1280 10564 0 0 0 0 01 0200 0200 0200 0002 0002 0002 0200 0200 0200 0200 0200 0002 0200 0002 0200 0200 0200 0200 0200 0200 0200 0200 0002 0002 0200 0002 0002 0002 0200 0200 0002 0200 03
```

**Comment by Icesory** [comment]
Yes so i see the patterns too. Feel free to change this by your self.

**Pull request closed without merging**
