### PR TITLE
Add weather12 for  a Globaltronic GT-WT-01 temperature/humidity sensor

### PR DESCRIPTION
**Pull request by hvdwolf**
This is the very first time I do something in pimatic and with coffeescript. Please check.
This relates to forum post http://forum.pimatic.org/topic/989/gt-wt-01-thermo-humidity-sensor-protocol

### CODE REVIEW

**Comment by hvdwolf** [comment]
It took some changes and bugfixes but it functions completely on my local setup.

**Comment by hvdwolf** [comment]
I'm also fairly sure about the weather12.coffee now. I ran it through http://js2.coffee/ and it seems correct.

**Comment by sweetpi** [comment]
Looks good. Could you add a test case in https://github.com/pimatic/rfcontroljs/blob/master/test/lib-controller.coffee or post a pulse sequence as example?

**Comment by hvdwolf** [comment]
I added 3 sequences.

**Pull request merged**
