### PR TITLE
Pull request for 2 new protocols

### PR DESCRIPTION
**Pull request by rolandkaeufl**
2 new protocols which only differ in the pulse length. One is for a rolling (Nobily) and the other is for a noname awning. Both types are "command".
commands for awning1: out, stop, in
commands for rolling2: up and down
both: id

If you find somewhere a commit called "Test Upload", please ignore and delete it :-)

### CODE REVIEW

**Comment by Icesory** [comment]
Sorry but the the rolling1 protocol is not for window roller! it is an special protocol which used a rolling code.
Please rename your protocol rolling2 to something other.

**Comment by Icesory** [comment]
and your rolling2 protocol has only 2 states, so it is a nomal switch protocol. Please change the type to switch and up to state true.

**Comment by rolandkaeufl** [comment]
Did the requested changes.

**Comment by Icesory** [comment]
Now it looks good. Thanks for your changes.

**Comment by rolandkaeufl** [comment]
Sorry for the lots of changes. Still fighting with git :-)

**Comment by sweetpi** [comment]
Hi @rolandkaeufl, thanks for the protocols. Could you do the following:

1. Backup your changed file to another location.
2. Run `git reset --hard 75c9243e30cbfd312b35afb732090cc9679b39ca` This will delete all your changes  and commit messages.
3. Copy back the changed files.
4. Commit them with `git add -A`, `git commit -a -m "Added awning and nobily protocols" `, `git push`. 

There's no need to recreate the pull request.

**Pull request merged**
