### PR TITLE
add Weather17

### PR DESCRIPTION
**Pull request by Schroedi71**
I hope it is all right :-)

https://forum.pimatic.org/topic/2183/how-can-add-a-new-protocol-for-updates

### CODE REVIEW

**Comment by mwittig** [comment]
Thanks for your PR. I'll not be able to add your PR as protocols shall be written in CS. The JS code is generated code. However, I can do that for you, but it'll be a manual transormation.

**Can you please add some debug output? I'd need this to generate some test cases.** Thanks!

**Comment by Schroedi71** [comment]
Sorry for the late reply.
I am a single parent with two children and a full-time job :-)

OK, I have it copied directly from the Pimatic-Deamon.log and hope it goes like this:
1. Temp:
08: 56: 05,127 [pimatic-homeduino] debug: data: "RF receive 1164 436 28660 0 0 0 0 0 0000000010001000000000000000101000000000001010100000000000000010001010100000000010100002"
08: 56: 05,131 [pimatic-homeduino] debug: received: [436, 1164, 28660] 1111111101110111111111111111010111111111110101011111111111111101110101011111111101011112
08: 56: 05,135 [pimatic-homeduino] debug: weatherTFA30: {id: 24, channel: 0, temperature: 20.1}

2.Temp:
10: 28: 36,888 [pimatic-homeduino] debug: data: "RF receive 1164 432 28600 0 0 0 0 0 0000000010001000000000000000101000000010001010100000100010000000001010100000100010000002"
10: 28: 36,894 [pimatic-homeduino] debug: received: [432, 1164, 28600] 1111111101110111111111111111010111111101110101011111011101111111110101011111011101111112
10: 28: 36,899 [pimatic-homeduino] debug: weatherTFA30: {id: 24, channel: 0, temperature: 22.8}



1.Humidity:
10: 32: 34,647 [pimatic-homeduino] debug: data: "RF receive 1164 436 28348 0 0 0 0 0 0000000010001000101010000000101000000010001010000000100000000000001010000000100010100002"
10: 32: 34,652 [pimatic-homeduino] debug: received: [436, 1164, 28348] 1111111101110111010101111111010111111101110101111111011111111111110101111111011101011112
10: 32: 34,658 [pimatic-homeduino] debug: weatherTFA30: {id: 24, channel 7, humidity: 62}

2.Humitidy:
10: 44: 17,563 [pimatic-homeduino] debug: data: "RF receive 1164 428 28096 0 0 0 0 0 0000000010001000101010000000101000000010001010000000001000000000001010000000001010001002"
10: 44: 17,568 [pimatic-homeduino] debug: received: [428, 1164, 28096] 1111111101110111010101111111010111111101110101111111110111111111110101111111110101110112
10: 44: 17,585 [pimatic-homeduino] debug: weatherTFA30: {id: 24, channel 7, humidity: 61}

Normal Humidity and Temperature will be sent directly to an other, but that does not make the Arduino somehow. I think due to the long footers? You might have as well as an idea which I then might like to try using the Arduino.

I have taken this thread as an aid to get it in Pimatic to run.
https://forum.pilight.org/Thread-TFA-30-3125-Temp-Hum-TFA-31-3120-90-Temp

Best wishes,
Frank

**Comment by mwittig** [comment]
HI Frank, thank you evry much for providing the debug data. I'll add test test cases now and will publish it along with two other weather protcols.

**Comment by mwittig** [comment]
Manually transformed to CS. See #111

**Pull request closed without merging**
