### PR TITLE
Adding support for yet an other Conrad weather sensor

### PR DESCRIPTION
**Pull request by thexperiments**

### CODE REVIEW

**Comment by sweetpi** [comment]
@thexperiments Please always edit / add coffee scribt files in src. Can you create the corresponding coffee file?

**Comment by mwittig** [comment]
What is the status of this, please? @thexperiments Are you in the position to make a new contribution written in coffeescript or did somebody added it meanwhile? Thanks

**Comment by mwittig** [comment]
@thexperiments I am not 100% sure on this one. I think the protocol never got added to rfcontroljs. If you can please post some debug output for different temperature and humidity values, I am happy to do the necessary coffeescript coding to get the protocol integrated. Thanks!

**Comment by mwittig** [comment]
Closed due to inactivity

**Pull request closed without merging**
