### PR TITLE
Added support for FA20RF smokedetectors

### PR DESCRIPTION
**Pull request by Xento**
When you switch the device on or off it will alert for about 5 seconds.
At the moment it is not possible that it stays on, because we need a new device definiton in pimatic.

### CODE REVIEW

**Comment by sweetpi** [comment]
Why the `encodeMessage` function? There is no use case for it or?

**Comment by Icesory** [comment]
The alarm of FA20RF can be triggered by an RF signal
https://github.com/pimatic/rfcontroljs/issues/35#issuecomment-74432923

**Comment by sweetpi** [comment]
@Icesory thanks, I missed that. Do you want to manage the rfcontroljs and homeduino repositories? I could give you access rights, so you can merge and push directly to them?

**Comment by Xento** [comment]
I added the coffescript files for this.

**Pull request merged**
